danielpalme/ReportGenerator

ReportGenerator.Reporting/Rendering/resources/custom.css
Hello Daniel,
I can't select correctly the tests from the `test methods` panel. When clicking on the radio button it is not detected neither on Firefox (40.0.3) or Chrome (45.0.2454.99).
Looking with the inspector on Firefox I noticed that the box of the heading of the panel overlaps with the radio buttons (see left side of the image below). After removing the height attribute and adjusting the position (left and top) as is done on the commit the issue is fixed (and the box has the correct size see right side of the image).
I'm not very happy with my solution, although it works, may be you have a better one?
Thank you
=> Change '#testmethods h2's css to avoid overlap with the test list.

ReportGenerator.Reporting/Properties/AssemblyInfo.cs, ReportGenerator/Generator.cs, ReportGenerator/IReportGenerator.cs, ReportGenerator/Logging/ConsoleLogger.cs, ReportGenerator/Logging/ConsoleLoggerFactory.cs, ReportGenerator/Logging/ILogger.cs, ReportGenerator/Logging/ILoggerFactory.cs, ReportGenerator/Logging/LoggerFactory.cs, ReportGenerator/Logging/VerbosityLevel.cs, ReportGenerator/MSBuild/ReportGenerator.cs, ReportGenerator/Program.cs, ReportGenerator/Properties/AssemblyInfo.cs, ReportGenerator/ReportConfiguration.cs, ReportGenerator/ReportGenerator.csproj, ReportGenerator/Reporting/IReportBuilderFactory.cs, ReportGeneratorTest/Properties/AssemblyInfo.cs
Hi. Could you consider my changes to be merged with the master line.
Recently I tried to use the ReportGenerator as a library for my project. What I wanted to do is to implement a bunch of my own report builders and a custom logging. I was using Autofac, not MEF for the composition.
Unfortunately, it is currently impossible to inject a custom logger factory or a report builder factory other than MEF-based since those interfaces are internal. Additionally, there is no way of executing the generation other than instantiating the ReportGenerator MSBuild task.
These limitations prevented me from extending the tool the way I wanted.
Please check whether my changes align with your design guidelines and would be good for the project as I'd rather not to publish a ReportGenerator2 on nuget.org …
=> Introduce extension points for builders and loggers.

ReportGenerator/Parser/Analysis/CodeFile.cs, ReportGeneratorTest/Parser/Analysis/CodeFileTest.cs
Hello,
I have created this pull request to fix the issue I currently have with running ReportGenerator on OpenCover xml reports.
The issue is that I have a xproj with unit tests that builds and tests my assembly with net451, net46 and netcoreapp1.1 framework in one go (I use dotnet test command for that). As an outcome of it, a single OpenCover report is generated with multiple entries for the same test method, and this causes ReportGenerator.exe to throw `System.ArgumentException: An item with the same key has already been added.`.
I fixed this issue with this PR.
=> Updated CodeFile.AddCoverageByTestMethod() to support duplicates in OpenCover reports

src/AzureDevopsTask/ReportGenerator/task.json, src/ReportGenerator.Core/ReportGenerator.Core.csproj, src/ReportGenerator.Core/Reporting/Builders/AzurePipelinesHtmlReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/Rendering/HtmlRenderer.cs, src/ReportGenerator.Core/Reporting/Builders/Rendering/resources/custom-azurepipelines.css
Closing #172 
I've added a custom ReportBuilder that uses a DIFFERENT CSS file, that is much more Azure Pipelines compliant.
It creates an InlineHtml report with the custom theme, so you can easily add it to VSTS / Azure Pipelines.
=> Azure pipelines render

src/ReportGenerator.Core/Reporting/Builders/Rendering/HtmlRenderer.cs
I have to integrate report generator with some legacy project. OpenCover output has about 140MB and 10.000 classes with code coverage. Report generation takes about 274 seconds. The hot point is HtmlRenderer.SaveJavaScript called by SaveClassReport. It is responsible for generating shared class.js file- it could be generated only once. After this simple optimisation report generation takes only 74 seconds.
=> Performance improvement- class.js is generated only once.

README.md, src/ReportGenerator.Core.Test/Parser/Analysis/CodeFileTest.cs, src/ReportGenerator.Core/Parser/Analysis/CodeFile.cs, src/ReportGenerator.Core/Reporting/Builders/Rendering/TeamCityRenderer.cs, src/ReportGenerator.Core/Reporting/Builders/TeamCitySummaryReportBuilder.cs
Teamcity allows import some coverage statistics to coverage tab [Sample](https://i2.wp.com/static.colinmackay.co.uk/images/team-city/2015-05-15-results-01.png). Without this simple renderer, I have to use some complex logic to extract this data from xml report. I hope this plugin will be useful for other users. Documentation of this feature [Reporting statistics](https://confluence.jetbrains.com/display/TCD18/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingBuildStatistics) &  [Keys](https://confluence.jetbrains.com/display/TCD18/Custom+Chart#CustomChart-predefinedStatisticsKeys)
=> New render for TeamCity

src/ReportGenerator.Console.NetCore/runtimeconfig.template.json, src/ReportGenerator.DotnetCliTool/runtimeconfig.template.json, src/ReportGenerator.DotnetGlobalTool/runtimeconfig.template.json
Allow roll-forward to .NET Core 3.0 if 2.x is not installed as-per https://github.com/danielpalme/ReportGenerator/pull/205#issuecomment-488252101.
I _think_ I've updated the right projects.
=> Allow runtime roll-forward

src/ReportGenerator.Core/Parser/Analysis/SummaryResult.cs, src/ReportGenerator.Core/Reporting/Builders/Rendering/HtmlRenderer.cs
#243 
> [`internal SummaryResult(IReadOnlyCollection<Assembly> assemblies, string usedParser, bool supportsBranchCoverage, IReadOnlyCollection<string> sourceDirectories)`](https://github.com/danielpalme/ReportGenerator/blob/46bd5f5f9709d29401b3bef849c65f3e2d04c017/src/ReportGenerator.Core/Parser/Analysis/SummaryResult.cs#L19)
>
> I'm trying to create an HTML report using the parsed result with `ReportGenerator.Core`. The class `HtmlReportBuilder` which takes `SummaryResult` as an argument whose constructor isn't exposed.
> 
> ![image](https://user-images.githubusercontent.com/4632805/58073460-3be03f00-7bc0-11e9-87c4-b250240129a8.png)
To create the report I realized we need to expose `HTMLRenderer` as well. Maybe there's a better way to create an HTMLReport from parsed result? If not then …
=> expose SummaryResult constructor and HtmlRenderer. fix #243

src/ReportGenerator.Core/Parser/CoberturaParser.cs
This fix works locally but I'm not sure of the implications or reasoning for the original filter.
Nested classes seem to be of the form `ParentClass/InnerClass` in the cobertura report.
This shows the result:
=> consider nested classes for line coverage

src/ReportGenerator.Core/ReportConfiguration.cs
I think the Hashset use will introduce unexpected behavior for others.   This minor change removes the duplicates, but keeps the order preserved
Disclaimer - I only edited the files via GitHub web interface - so it may not build :-)    But you should get the idea
=> Preserve Found Order

src/ReportGenerator.Core/Parser/CloverParser.cs
For source files that are contained in a single folder, jest doesn't create the `<package>` node in the clover xml and parsing generates no results.
Sample clover xml.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1566893974275" clover="3.2.0">
<project timestamp="1566893974275" name="All files">
<metrics statements="3" coveredstatements="3" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="1" elements="4" coveredelements="4" complexity="0" loc="3" ncloc="3" packages="1" files="1" classes="1"/>
<file name="app.js" path="D:\jestcoverage\app.js">
<metrics statements="3" coveredstatements="3" conditionals="0" coveredconditionals="0" methods="1" coveredmethods="1"/>
<line num="1" count="1" type="stmt"/>
<line num="2" count="1" type="stmt"/>
<line …
```
=> Fix for when clover does not contain package element

src/ReportGenerator.Core/Reporting/Builders/LCovSummaryReportBuilder.cs
Branches stats should be reported with a PostFix of 'R' according to this https://www.jetbrains.com/help/teamcity/custom-chart.html#Default-Statistics-Values-Provided-by-TeamCity
=> Fixing a bug, branch stats reported as blocks

src/ReportGenerator.Core/Reporting/Builders/Rendering/HtmlRenderer.cs
I noticed I was getting some 404's when using the inline html formats that were coming from `background-image: url()` elements like [this one](https://github.com/danielpalme/ReportGenerator/blob/d63c8c22da01955281c5cabf95966a68cadd36ea/src/ReportGenerator.Core/Reporting/Builders/Rendering/resources/custom-azurepipelines.css#L268) . This strips them out when getting the combined css for an inline HTML report.
Another possibility is to remove the non-inlined version of these background-image elements; 
they appear to be same data as the uris, as they're used to write out the images in non-inline reports:
https://github.com/danielpalme/ReportGenerator/blob/d63c8c22da01955281c5cabf95966a68cadd36ea/src/ReportGenerator.Core/Reporting/Builders/Rendering/HtmlRenderer.cs#L1305-L1318
But if I know …
=> Only write data urls in combined CSS for inline HtmlRenderers

src/ReportGenerator.Core/Parser/OpenCoverParser.cs
Use the correct variable for visit count when adding visits to an existing Branch object.
=> Fix class-level branch coverage for OpenCover reports

src/ReportGenerator.Core/Parser/CoverageReportParser.cs
Report Generator tries to read first line of coverage file into memory in order to determine if it's XML or text; however in my case I have 2-2.5 GB files without line breaks, which causes OutOfMemory exception
=> Fix reading large XML coverage files (crash on 2GB files)

src/ReportGenerator.Core/Reporting/Builders/CloverReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/CoberturaReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/SonarQubeBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/XmlReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/XmlSummaryReportBuilder.cs, src/ReportGenerator.Core/Reporting/History/HistoryReportGenerator.cs
Attempt at fixing https://github.com/danielpalme/ReportGenerator/issues/380, if the issue is valid for the project :)
cc @danielpalme
=> Update all calls to XDocument.Save to use an XmlTextWriter without a UTF-8 BOM encoding.

src/ReportGenerator.Core.Test/FileManager.cs, src/ReportGenerator.Core.Test/MsBuildTest.cs, src/ReportGenerator.Core.Test/ReportGenerator.Core.Test.csproj
Instead of directory probing, just use assembly metadata to persist the
project directory where the test project files are. Quicker and also
more reliable.
Also, always generate binlogs for MSBuild tests, for troubleshooting
purposes.
=> Improve reliability and logging for MSBuild tests

src/ReportGenerator.Console/ReportGenerator.Console.Net.csproj
This allows building the project without requiring any SDK setups.
=> Remove unnecessary .NET bootstrapper and use reference assemblies instead

README.md, src/ReportGenerator.Core.Test/ReportConfigurationBuilderTest.cs, src/ReportGenerator.Core/ReportConfigurationBuilder.cs, src/ReportGenerator.Core/ReportGenerator.Core.csproj, src/ReportGenerator.MSBuild/ReportGenerator.cs
The http://dotnetconfig.org/ format allows unifying configuration with
other .NET core tools, making it easier to maintain multiple tool settings
in a centralized fashion.
By leveraging the format, ReportGenerator gains:
* Simplified command line args in CI scripts (just run without parameters
most of the time)
* Support for hierarchical configurations
* Standard way of updating and managing those configurations, via the
`dotnet config` tool, such as `dotnet config --add reportgenerator.reporttype Html`
The configuration is shared uniformly between the CLI and MSBuild task, for
consistency. Updated the documentation too to showcase the new functionality.
=> Add support for reading report arguments from .netconfig

src/ReportGenerator.Core/Parser/Preprocessing/CoberturaReportPreprocessor.cs
Fixes the issue of generating double directory separators from cobertura reports, when switching OS between coverage data and report generation.
Problem exists when the cobertura report is generated on a windows machine, but ReportGenerator runs on linux machine.
- the cobertura coverage result contains file paths windows style e.g. 'C:\builds\src\Download\', 'Test.cs'
- calling Path.Combine on a linux system afterwards results in 'C:\builds\src\Download\/Test.cs'
- which gets edited with Replace to 'C:/builds/src/Download//Test.cs'
Adapting the path strings to the current OS before Path.Combine fixes this issue.
=> fix: clean up directory separators before path combine

src/ReportGenerator.Core/Parser/DynamicCodeCoverageParser.cs, src/ReportGenerator.Core/Reporting/Builders/Rendering/HtmlRenderer.cs
Thanks for creating this great tool!
Regarding this PR: In our scenarios, we have one DLL that built separately for x86 and x64. Then we run our tests against this DLL on x86 machines and x64 machines separately, also collect the code coverage data using VSTest.console.exe from Visual Studio. Eventually, we merge all the code coverage files into one file. This resulted in 2 modules (actually same module for different architectures) with the same assembly name with different IDs in the merged file.
Although ReportGenerator is able to handle multiple assemblies, but it expects the assemblies' name to be unique. Our data fails this expectation, and the report generated by ReportGenerator is mixing the coverage data from different modules together. 
Another issue is that, when multiple source …
=> Fix issues with handling of multiple assemblies with the same name

src/ReportGenerator.Core/ReportGenerator.Core.csproj
See https://github.com/dotnet/runtime/issues/49377 - Microsoft Security Advisory CVE-2021-26701 | .NET Core Remote Code Execution Vulnerability 
5.0.0 was used for System.Text.Encodings.Web, updated to 5.0.1
Also updated DotNetConfig package to a non-preview version
Needed for dotnet-reportgenerator-globaltool
See also report Nexus IQ (sorry no public link)
=> [Security] Fix CVE-2021-26701 (Remote Code Execution Vulnerability) and update DotNetConfig to RTM

src/ReportGenerator.Core/Properties/Resources.resx
The text "The report file pattern '{0}' is invalid" is confusing. The pattern itself isn't invalid. 
Example:
-reports:**/*cobertura*.xml;**/*opencover*.xml;
Will give now: `The report file pattern "**/*cobertura*.xml ' is invalid` - which is confusing 
note: This a generic template and we let the user decide if it uses opencover or cobertura
=> Improve text of FailedReportFilePattern

src/ReportGenerator.Core/Reporting/Builders/Rendering/resources/custom.css
Let me start out by saying that I love this tool.
I've recently started using it to generate reports on code coverage. One thing stood out to me though. When dark mode preference is set in the browser and the report loads in dark mode, the header rows for namespaces are a really light color. (I think it was just missed probably) like in this screenshot.
. 
With my change I believe I have fixed the issue
.
If you could take a look at this, I would greatly appreciate it. And I'm open to any suggestions on what else I can do.
Thanks!
=> color change of header rows for dark mode preference users

src/ReportGenerator.Core/Reporting/Builders/CsvSummaryReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/LCovSummaryReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/MarkdownDeltaSummaryReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/MarkdownSummaryReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/TextDeltaSummaryReportBuilder.cs, src/ReportGenerator.Core/Reporting/Builders/TextSummaryReportBuilder.cs
This PR proposes to remove the UTF-8 BOM from the text reports. The BOM doesn't add much value in them yet avoids problems with programs that don't work well with its presence. If ever really needed, it could be added back via a CLI option.
=> Generate text reports without UTF-8 BOM

src/ReportGenerator.Core/Reporting/Builders/SonarQubeBuilder.cs
When using multiple coverage reports as input for the SonarQube format, then the coverage is not correctly merged.
The reason for this is that the SonarCubeBuilder skips the whole file if an existing line is found in an existing file.
With this PR this behavior is fixed, so that only the existing line is not added a second time.
=> Only skip the found line, not the whole file

src/.gitignore, src/ReportGenerator.Core.Test/Parser/CoberturaParserTest.cs, src/ReportGenerator.Core/Parser/CoberturaParser.cs
Added a calculated figure for CRAP score for cobertura coverage reports.  Also slight refactoring of the Cobertura metrics calculations to reduce repetition of parsing code.
closes #641
=> Added a calculated figure for CRAP score for cobertura reports.

src/AngularComponents/src/app/components/coverageinfo/coverage-info.component.ts, src/AngularComponents/src/app/components/riskhotspots/riskhotspots.component.ts
Risk hotspots and coverage info tables' triangle icons show incorrect sorting direction.
The triangles represent a stack of items like a [Tower of Hanoi](https://en.wikipedia.org/wiki/Tower_of_Hanoi) toy.
- An upwards-pointing triangle ▲ represents a stack with the narrowest (ie, smallest) item on top and the widest (ie, largest) item on the bottom, hence an ascending list.
- A downwards-pointing triangle ▼ represents a stack with the widest (ie, largest) item on top and the narrowest (ie, smallest) item on the bottom, hence a descending list.
=> Fix sort direction triangles

src/ReportGenerator.Core/Parser/CoberturaParser.cs
- Try and re-use already filtered XElements in `CoberturaParser` rather than re-filtering the xml document all over the place.
- Optimise some `string.Concat` in `ProcessClass` method which were showing up in hot paths in profiling
In local testing, this reduces parsing time from roughly 11.5secs to 9 seconds, as well as reducing memory allocations from  17GB to 2.2GB.
For reference below is the code I tested with
```cs
string[] coverageFiles = { /* Test files */ };
CoverageReportParser parser = new CoverageReportParser(1, 1, [],
new DefaultFilter([]),
new DefaultFilter([]),
new DefaultFilter([]));
ReadOnlyCollection<string> collection = new(coverageFiles);
var stopwatch = Stopwatch.StartNew();
var results = parser.ParseFiles(collection);
var lines = results.Assemblies.Select(x => …
```
=> Performance improvements to CoberturaParser

src/ReportGenerator.Core/Parser/Analysis/Assembly.cs
Fixes #690, specifically around merging of reports with non unique class names.
Extends the fix from 78a1a92 to also apply to merging.
=> Fix merging of classes with non unique names.

src/ReportGenerator.Core/ReportGenerator.Core.csproj, src/ReportGenerator.Core/Reporting/Builders/Rendering/HtmlRenderer.cs
This is mainly done by avoiding creating additional `StringBuilder`s and writing direct to the `TextWriter` where possible. Where `StringBuilder`s are still needed, they're pooled and reused
Saves on the amount of allocated memory and time paused for GC.
I haven't measured a huge improvement in end to end report generation (maybe a second, but hard to say if that's within run to run variance), however reduction in allocations helps and this change does have measurable impacts when combined with my next PR.
Below are the perfview Results with my playground - built on top of the app from #691 with an an additional call to `ReportGenerator.GenerateReport`.  
```cs
// Generate the html report with custom configuration for report generator.
var reportGeneratorConfig = new …
```
=> Optimise memory allocations in `HtmlRenderer`.

src/ReportGenerator.Core/Reporting/Builders/TextSummaryReportBuilder.cs
2 numbers makes a difference for large code base
(Usefull in Gitlab where you can check coverage before validating a Merge Request)
See https://docs.gitlab.com/ee/ci/testing/code_coverage.html#test-coverage-examples
Can be up to 2 digits
=> Increase precision to 2 digits (2.3% => 2.34%)

src/ReportGenerator.Core.Test/Common/StringExtensionsTest.cs, src/ReportGenerator.Core/Common/StringExtensions.cs, src/ReportGenerator.Core/ReportConfigurationBuilder.cs, src/ReportGenerator.MSBuild/ReportGenerator.cs
This should fix https://github.com/danielpalme/ReportGenerator-GitHub-Action/issues/22 by implementing a new splitting method that is aware of curly braces since they are used in group conditions in globs.
I couldn't run all the tests locally though since I'm on a mac and a lot of the tests uses file paths with \ in them.
=> Fixed splitting of possible glob patterns
